print ("Evaluación Nº1 de Programación y Redes VIrtualizadas hecho por Cristobal Illanes")
Nombre = input("Ingrese su nombre: ")
Apellido =input("Ingrese su apellido: ")
Sección =input("Ingrese el codigo de la Asignatura y sección: ")
Sede =input("Ingrese su sede: ")
print ("Hola usted es ", Nombre, Apellido + " de la asignatura y  Sección ", Sección + " y de la sede", Sede)
